# Generated by Django 4.2 on 2023-04-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_posts_tags_profile_posts_tags_like_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profiletag',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
