# Generated by Django 4.2 on 2023-04-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.like'),
        ),
    ]
