# Generated by Django 4.2 on 2023-05-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_favorite_posts_favorite_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='post',
            new_name='posts',
        ),
    ]
