# Generated by Django 4.2 on 2023-05-14 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_post_favorite_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='posts',
        ),
        migrations.AddField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_favorites', to='core.posts'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
